Sewing/Models/Poco/Material_supply.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;

namespace ConsoleApp.Models
{
    public class Material_supply
    {
        [Key]
        public int Id { get; set; }
        public int MaterialSupplyId { get; set; }
        public string Provider { get; set; }
        public string MaterialSupply_name { get; set; }
        public decimal Price_of_materials { get; set; }
        public int Amount_of_material { get; set; }
        public DateTime Delivery_data { get; set; }
        //public Material Material { get; set; }

        public Material_supply(int id, int materialId, string provider, string materials_name,
            decimal price_of_materials, int amount_of_materials, DateTime delivery_data)
        {
            Id = id;
            //MaterialSupplyId = materialId;
            Provider = provider;
            MaterialSupply_name = materials_name;
            Price_of_materials = price_of_materials;
            Amount_of_material = amount_of_materials;
            Delivery_data = delivery_data;
        }

        public Material_supply() { }
    }
}

Sewing/Controllers/Material_supplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ConsoleApp.Models;
using Sewing.Data;
using Sewing.Models.ViewModel;
using FuelStation.Services;
//•	Классы контроллеров (по одному на каждую таблицу базы данных) для обработки обраще-ний пользователя,
//выборки данных из таблиц и вызова соответствующих представлений для отображения выбранных данных.
namespace Sewing.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class Material_supplyController : Controller
    {
        private readonly int _size = 20;
        private readonly SewingContext _context;
        private readonly CachedService _cachedService;

        public Material_supplyController(SewingContext context, CachedService cachedService)
        {
            _context = context;
            _cachedService = cachedService;
        }

        // GET: api/Material_supply
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Material_supply>>> GetMaterial_supply([FromQuery] int page = 1)
        {
            page--;
            var cnt = _context.Material_supply.Count();
            return View("Get", new DataViewModel<Material_supply>()
            {
                Data = _cachedService.GetMaterialSupply(page,_size),
                PageCount = cnt / _size + (cnt % _size > 0 ? 1 : 0),
                CurrentPage = page
            });
        }


        // PUT: api/Material_supply/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutMaterial_supply(int id, Material_supply material_supply)
        {
            if (id != material_supply.Id)
            {
                return BadRequest();
            }

            _context.Entry(material_supply).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!Material_supplyExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Material_supply
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Material_supply>> PostMaterial_supply(Material_supply material_supply)
        {
            _context.Material_supply.Add(material_supply);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetMaterial_supply", new { id = material_supply.Id }, material_supply);
        }

        // DELETE: api/Material_supply/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Material_supply>> DeleteMaterial_supply(int id)
        {
            var material_supply = await _context.Material_supply.FindAsync(id);
            if (material_supply == null)
            {
                return NotFound();
            }

            _context.Material_supply.Remove(material_supply);
            await _context.SaveChangesAsync();

            return material_supply;
        }

        private bool Material_supplyExists(int id)
        {
            return _context.Material_supply.Any(e => e.Id == id);
        }
    }
}

Sewing/Views/Material_supply/Get.cshtml
@using Sewing.Models.ViewModel;
@model DataViewModel<ConsoleApp.Models.Material_supply>

@{
    ViewData["Title"] = "Get";
}

<h1>Get</h1>

<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Data.First().Material.Materials_name)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Provider)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().MaterialSupply_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Price_of_materials)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Amount_of_material)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Delivery_data)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Material.Materials_name)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Provider)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaterialSupply_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price_of_materials)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount_of_material)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Delivery_data)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <ul class="pagination">
        @{
            var minval = Model.CurrentPage - 5 > 1 ? Model.CurrentPage - 5 : 1;
            if (minval > 1)
            {
                <li class="page-item">
                    <a asp-action="GetMaterial_supply" asp-controller="Material_supplyt" asp-route-page="1" class="page-link">1</a>
                </li>
            }
        }

        @for (var i = 0; i < 10 && minval <= Model.PageCount; i++, minval++)
        {

            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                <a asp-action="GetMaterial_supply" asp-controller="Material_supply" asp-route-page=@(minval) class="page-link">@minval</a>
            </li>
        }
        @if (minval < Model.PageCount)
        {
            <li class="page-item">
                <a asp-action="GetMaterial_supply" asp-controller="Material_supply" asp-route-page=@Model.PageCount class="page-link">@Model.PageCount</a>
            </li>
        }
    </ul>
</div>