Sewing/Models/Poco/Product.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ConsoleApp.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        public int MaterialId { get; set; }
        public string Product_name { get; set; }
        public string Materials_name { get; set; }
        public int Amount_of_material { get; set; }
        public decimal Price_of_product { get; set; }
        public Material Material { get; set; }

        public List<Order> Orders { get; set; }

        public Product(int id, int materialId, string product_name,
            string materials_name, int amount_of_material, decimal price_of_product)
        {
            Id = Id;
            MaterialId = materialId;
            Product_name = product_name;
            Materials_name = materials_name;
            Amount_of_material = amount_of_material;
            Price_of_product = price_of_product;

        }

        public Product() { }
    }
}

Sewing/Controllers/Atelier_departmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ConsoleApp.Models;
using Sewing.Data;
using Sewing.Models.ViewModel;
using FuelStation.Services;
//Классы контроллеров (по одному на каждую таблицу базы данных) для обработки обраще-ний пользователя,
//выборки данных из таблиц и вызова соответствующих представлений для отображения выбранных данных.
namespace Sewing.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class Atelier_departmentController : Controller
    {
        private readonly int _size = 20;
        private readonly SewingContext _context;
        private readonly CachedService _cachedService;

        public Atelier_departmentController(SewingContext context, CachedService cachedService)
        {
            _context = context;
            _cachedService = cachedService;
        }

        // GET: api/Atelier_department
        [HttpGet]
        public async Task<ActionResult<DataViewModel<Atelier_department>>> GetAtelier_department([FromQuery] int page = 1)
        {
            page--;
            var cnt = _context.Atelier_Departments.Count();
            return View("Get",new DataViewModel<Atelier_department>()
            {
                Data = _cachedService.GetAtelier_department(page,_size),
                PageCount = cnt / _size + (cnt%_size > 0? 1:0),
                CurrentPage = page
            });
        }


        // PUT: api/Atelier_department/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutAtelier_department(int id, Atelier_department atelier_department)
        {
            if (id != atelier_department.Id)
            {
                return BadRequest();
            }

            _context.Entry(atelier_department).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!Atelier_departmentExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Atelier_department
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Atelier_department>> PostAtelier_department(Atelier_department atelier_department)
        {
            _context.Atelier_Departments.Add(atelier_department);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetAtelier_department", new { id = atelier_department.Id }, atelier_department);
        }

        // DELETE: api/Atelier_department/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Atelier_department>> DeleteAtelier_department(int id)
        {
            var atelier_department = await _context.Atelier_Departments.FindAsync(id);
            if (atelier_department == null)
            {
                return NotFound();
            }

            _context.Atelier_Departments.Remove(atelier_department);
            await _context.SaveChangesAsync();

            return atelier_department;
        }

        private bool Atelier_departmentExists(int id)
        {
            return _context.Atelier_Departments.Any(e => e.Id == id);
        }
    }
}

Sewing/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ConsoleApp.Models;
using Sewing.Data;

namespace Sewing.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ProductsController : ControllerBase
    {
        private readonly SewingContext _context;

        public ProductsController(SewingContext context)
        {
            _context = context;
        }

        // GET: api/Products
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Product>>> GetProducts()
        {
            return await _context.Products.ToListAsync();
        }

        // GET: api/Products/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Product>> GetProduct(int id)
        {
            var product = await _context.Products.FindAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            return product;
        }

        // PUT: api/Products/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutProduct(int id, Product product)
        {
            if (id != product.Id)
            {
                return BadRequest();
            }

            _context.Entry(product).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Products
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Product>> PostProduct(Product product)
        {
            _context.Products.Add(product);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetProduct", new { id = product.Id }, product);
        }

        // DELETE: api/Products/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Product>> DeleteProduct(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            _context.Products.Remove(product);
            await _context.SaveChangesAsync();

            return product;
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

Sewing/Views/Products/Get.cshtml
@using Sewing.Models.ViewModel;
@model DataViewModel<ConsoleApp.Models.Product>

@{
    ViewData["Title"] = "Get";
}

<h1>Get</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Product_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Materials_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Amount_of_material)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Price_of_product)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Material)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Materials_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount_of_material)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price_of_product)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Material.Id)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <ul class="pagination">
        @{
            var minval = Model.CurrentPage - 5 > 1 ? Model.CurrentPage - 5 : 1;
            if (minval > 1)
            {
                <li class="page-item">
                    <a asp-action="GetAtelier_department" asp-controller="Atelier_department" asp-route-page="1" class="page-link">1</a>
                </li>
            }
        }

        @for (var i = 0; i < 10 && minval <= Model.PageCount; i++, minval++)
        {

            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                <a asp-action="GetAtelier_department" asp-controller="Atelier_department" asp-route-page=@(minval) class="page-link">@minval</a>
            </li>
        }
        @if (minval < Model.PageCount)
        {
            <li class="page-item">
                <a asp-action="GetAtelier_department" asp-controller="Atelier_department" asp-route-page=@Model.PageCount class="page-link">@Model.PageCount</a>
            </li>
        }
    </ul>
</div>