Sewing/Models/Poco/Material.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ConsoleApp.Models
{
    public class Material
    {
        [Key]
        public int Id { get; set; }
        public string Materials_name { get; set; }
        public string Types_of_materials { get; set; }
        public int Number_of_stock { get; set; }

        //public List<Material_supply> MaterialSupply { get; set; }

        public List<Product> Products { get; set; }

        public Material(int id, string materials_name, string types_of_materials, int number_of_stock)
        {
            Id = id;
            Materials_name = materials_name;
            Types_of_materials = types_of_materials;
            Number_of_stock = number_of_stock;
        }

        public Material() { }
    }
}

Sewing/Controllers/MaterialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ConsoleApp.Models;
using Sewing.Data;
using Sewing.Models.ViewModel;
using FuelStation.Services;
//•	Классы контроллеров (по одному на каждую таблицу базы данных) для обработки обраще-ний пользователя, 
//выборки данных из таблиц и вызова соответствующих представлений для отображения выбранных данных.
namespace Sewing.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class MaterialsController : Controller
    {
        private readonly int _size = 20;
        private readonly SewingContext _context;
        private readonly CachedService _cachedService;

        public MaterialsController(SewingContext context, CachedService cachedService)
        {
            _context = context;
            _cachedService = cachedService;
        }

        // GET: api/Materials
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Material>>> GetMaterials([FromQuery] int page = 1)
        {
            page--;
            var cnt = _context.Materials.Count();
            return View("Get", new DataViewModel<Material>()
            {
                Data = _cachedService.GetMaterial(page,_size),
                PageCount = cnt / _size + (cnt % _size > 0 ? 1 : 0),
                CurrentPage = page
            }); ;
        }


        // PUT: api/Materials/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutMaterial(int id, Material material)
        {
            if (id != material.Id)
            {
                return BadRequest();
            }

            _context.Entry(material).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MaterialExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Materials
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Material>> PostMaterial(Material material)
        {
            _context.Materials.Add(material);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetMaterial", new { id = material.Id }, material);
        }

        // DELETE: api/Materials/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Material>> DeleteMaterial(int id)
        {
            var material = await _context.Materials.FindAsync(id);
            if (material == null)
            {
                return NotFound();
            }

            _context.Materials.Remove(material);
            await _context.SaveChangesAsync();

            return material;
        }

        private bool MaterialExists(int id)
        {
            return _context.Materials.Any(e => e.Id == id);
        }
    }
}

Sewing/Views/Materials/Get.cshtml
@using Sewing.Models.ViewModel;
@model DataViewModel<ConsoleApp.Models.Material>

@{
    ViewData["Title"] = "Get";
}

<h1>Get</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Materials_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Types_of_materials)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data.First().Number_of_stock)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Materials_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Types_of_materials)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Number_of_stock)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <ul class="pagination">
        @{
            var minval = Model.CurrentPage - 5 > 1 ? Model.CurrentPage - 5 : 1;
            if (minval > 1)
            {
                <li class="page-item">
                    <a asp-action="GetMaterials" asp-controller="Materials" asp-route-page="1" class="page-link">1</a>
                </li>
            }
        }

        @for (var i = 0; i < 10 && minval <= Model.PageCount; i++, minval++)
        {

            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                <a asp-action="GetMaterials" asp-controller="Materials" asp-route-page=@(minval) class="page-link">@minval</a>
            </li>
        }
        @if (minval < Model.PageCount)
        {
            <li class="page-item">
                <a asp-action="GetMaterials" asp-controller="Materials" asp-route-page=@Model.PageCount class="page-link">@Model.PageCount</a>
            </li>
        }
    </ul>
</div>